version: '3'
services:
  jenkins:
    image: pz/jenkins
    ports:
    - "8080:8080"
    links:
    - sonarqube
  sonarqube:
    image: sonarqube
    ports:
    - "9000:9000"
    volumes:
    - /opt/sonarqube/conf
    - /opt/sonarqube/data
    - /opt/sonarqube/extensions
    - /opt/sonarqube/lib/bundled-plugins
    links:
    - postgres
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
    - /var/lib/postgresql
    - /var/lib/postgresql/data
    
    

    